version: "3.8"
services:
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: Root18!
      MYSQL_DATABASE: tripfinity
    ports:
      - "3308:3306"
    networks:
      - tripfinity-network

  backend_service:
    container_name: backendservice
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tripfinity
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root18!
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - tripfinity-network

  ui_service:
    #    restart: always
    build:
      context: D:/BDTS-Master/Anul2/Diseratatie/tripfinityUI
      dockerfile: Dockerfile
    depends_on:
      - backend_service
    networks:
      - tripfinity-network
    ports:
      - "4200:4200"

networks:
  tripfinity-network:
    driver: bridge